# These settings were set by the catalyst build script that automatically
# built this stage.
# Please consult /usr/share/portage/config/make.conf.example for a more
# detailed example.
COMMON_FLAGS="-march=native -O2 -pipe"
CFLAGS="${COMMON_FLAGS}"
CXXFLAGS="${COMMON_FLAGS}"
FCFLAGS="${COMMON_FLAGS}"
FFLAGS="${COMMON_FLAGS}"
LDFLAGS="-Wl,-O2 -Wl,--as-needed"
RUSTFLAGS="-C debuginfo=0 -C codegen-units=1 -C target-cpu=native -C opt-level=3"

# NOTE: This stage was built with the bindist USE flag enabled

# This sets the language of build output to English.
# Please keep this setting intact when reporting bugs.
LC_MESSAGES=C.UTF-8

MAKEOPTS="-j16 -l16"
ACCEPT_LICENSE="*"
USE="-* minimal video_cards_amdgpu vulkan wayland pipewire native-symlinks lto pgo jit xs orc threads asm openmp system-man system-libyaml system-lua system-bootstrap system-llvm system-lz4 system-sqlite system-ffmpeg system-icu system-av1 system-harfbuzz system-jpeg system-libevent system-librnp system-libvpx system-png system-python-libs system-webp system-ssl system-zlib system-boost"
VIDEO_CARDS="radeonsi amgpu"
ACCEPT_KEYWORDS="~amd64"

PYTHON_TARGETS="python3_14"
PYTHON_SINGLE_TARGET="python3_14"
LUA_SINGLE_TARGET="lua5-4"

GENTOO_MIRRORS="https://gentoo.zero.com.ar/gentoo/ \
    https://gentoo.c3sl.ufpr.br/ \
    https://br.mirrors.cicku.me/gentoo/ \
    https://umbriel.br.ext.planetunix.net/pub/gentoo/"
CPU_FLAGS_X86="aes avx avx2 bmi1 bmi2 f16c fma3 mmx mmxext pclmul popcnt rdrand sha sse sse2 sse3 sse4_1 sse4_2 sse4a ssse3 vpclmulqdq"
